[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Frame-Options = "sameorigin"
    X-XSS-Protection= "1; mode=block"
    X-Content-Type-Options= "nosniff"
    Referrer-Policy= "same-origin"
    X-Robots-Tag = "index"
    cache-control = "public, max-age=0, no-cache, no-store, must-revalidate"
    Content-Security-Policy= "frame-ancestors 'sameorigin' https://www.flightradar24.com"