[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    X-XSS-Protection= "1; mode=block"
    X-Content-Type-Options= "nosniff"
    cache-control = "public, max-age=0, no-cache, no-store, must-revalidate"
    Content-Security-Policy= "frame-ancestors 'sameorigin' https://www.flightradar24.com https://flightradar24.com https://flightradar24.muller.tel"